stages:
  preprocess:
    cmd: python3 preprocess_dataset.py
    deps:
    - preprocess_dataset.py
    - raw_dataset/weather.csv
    - utils_and_constants.py
    outs:
    - processed_dataset/weather.csv
  hp_tune:
    # Set the hyperparameter tuning command
    cmd: python3 hp_tuning.py
    deps:
    - processed_dataset/weather.csv
    # Specify the hyperparameter configuration as dependency
    - hp_config.json
    # Specify the hyperparameter script as dependency
    - hp_tuning.py
    - utils_and_constants.py
    outs:
      - hp_tuning_results.md:
          cache: false
  train:
    cmd: python3 train.py
    deps:
    - metrics_and_plots.py
    - model.py
    - processed_dataset/weather.csv
    - rfc_best_params.json
    - train.py
    - utils_and_constants.py
    metrics:
      - metrics.json:
          cache: false
    plots:
    - predictions.csv:
        template: confusion
        x: predicted_label
        y: true_label
        x_label: 'Predicted label'
        y_label: 'True label'
        title: Confusion matrix
        cache: false
    - roc_curve.csv:
        template: simple
        x: fpr
        y: tpr
        x_label: 'False Positive Rate'
        y_label: 'True Positive Rate'
        title: ROC curve
        cache: false
