name: hp-tuning

on:
  pull_request:
    branches: main

permissions: write-all

jobs:
  hp_tune:
    if: startsWith(github.head_ref, 'hp_tune/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.16

      - name: Setup CML
        uses: iterative/setup-cml@v1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-root
          # pip install dvc[s3]

      - name: Run DVC pipeline
        run: |
          poetry run dvc repro -f preprocess
          poetry run dvc repro -f hp_tune
      
      - name: Create training branch
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml comment create hp_tuning_results.md
          export BRANCH_NAME=train/$(git rev-parse --short "${{ github.sha }}")
          cml pr create --user-email hp-bot@cicd.ai --user-name HPBot --message "HP tuning" --branch $BRANCH_NAME rfc_best_params.json
